apiVersion: v1
kind: Namespace
metadata:
  name: rancher-exporter
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rancher-exporter
  namespace: rancher-exporter
spec:
  selector:
    matchLabels:
      app: rancher-exporter
  template:
    metadata:
      labels:
        app: rancher-exporter
    spec:
      containers:
        - imagePullPolicy: Always
          name: rancher-exporter
          image: virtualthoughts/prometheus-rancher-exporter:0.1
          ports:
            - name: metrics
              protocol: TCP
              containerPort: 8080
  replicas: 1
---
apiVersion: v1
kind: Service
metadata:
  name: rancher-exporter
  namespace: rancher-exporter
  labels:
    app: rancher-exporter
spec:
  selector:
    app: rancher-exporter
  ports:
    - name: metrics
      port: 80
      protocol: TCP
      targetPort: metrics
  type: ClusterIP
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: rancher-exporter
  namespace: rancher-exporter
spec:
  selector:
    matchLabels:
      app: rancher-exporter
  endpoints:
    - port: metrics
      path: /metrics